# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincent', '0005_comment_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='long_line',
            field=models.BooleanField(default=False),
        ),
    ]
