# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 17:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vincent', '0006_auto_20160423_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfilled', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('polling_location', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='vincent.GeocodedPollingLocation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
