# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vincent', '0007_assignedlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreport',
            name='status',
            field=models.CharField(choices=[(b'new', b'New'), (b'assigned', b'Assigned'), (b'resolved', b'Resolved'), (b'closed', b'Closed')], default=b'new', max_length=32),
        ),
    ]
