# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-24 21:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vincent', '0008_auto_20160423_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 24, 21, 35, 54, 801406, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
