# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('vincent', '0009_incidentreport_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='reporter_role',
            field=models.CharField(blank=True, choices=[(b'voter', b'Voter'), (b'staff', b'Staff'), (b'legal-volunteer', b'Legal Volunteer'), (b'other', b'Other')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='creator_phone',
            field=localflavor.us.models.PhoneNumberField(max_length=20),
        ),
    ]
